
export default {
    INSERT_ITEM: 'INSERT_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    INSERT_SECTION: 'INSERT_SECTION',
    DELETE_SECTION: 'DELETE_SECTION',
    UPDATE_SECTION: 'UPDATE_SECTION',
    TOGGLE_EDIT_SECTION: 'TOGGLE_EDIT_SECTION',
}