
export default {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    ADD_SECTION: 'ADD_SECTION',
    DELETE_SECTION: 'DELETE_SECTION',
    UPDATE_SECTION: 'UPDATE_SECTION',
    TOGGLE_EDIT_SECTION: 'TOGGLE_EDIT_SECTION',
}